generate_metdir: True

namelist_ungrib_atm:
  class: File
  path: 'ungrib_test_input/namelist.wps.ungrib_atm'

vtable_atm:
  class: File
  path: 'ungrib_test_input/Vtable.ECATM'
    
outname_atm: 'ATMFILE'
  
grib_files_atm:
  - class: File
    path: 'ungrib_test_input/preslev_201812.grib'
  - class: File
    path: 'ungrib_test_input/preslev_201901.grib'


namelist_ungrib_sfc:
  class: File
  path: 'ungrib_test_input/namelist.wps.ungrib_sfc'

vtable_sfc:
  class: File
  path: 'ungrib_test_input/Vtable.ECSFC'
    
outname_sfc: 'SFCFILE'
  
grib_files_sfc:
  - class: File
    path: 'ungrib_test_input/surface_201812.grib'
  - class: File
    path: 'ungrib_test_input/surface_201901.grib'


geo_file_uk9km:
  class: File
  path: 'ungrib_test_input/geo_em.d01.nc.UK_9km'

namelist_metgrid_uk9km:
  class: File
  path: 'ungrib_test_input/namelist.wps.emep_uk9km'


geo_file_emep50km:
  class: File
  path: 'ungrib_test_input/geo_em.d01.nc.EMEP_50km'

namelist_metgrid_emep50km:
  class: File
  path: 'ungrib_test_input/namelist.wps.emep_50km'



#cwltool:overrides:
#  ungrib.cwl:
#    requirements:
#      DockerRequirement:
#        dockerPull: douglowe/wrf-docker:latest
