generate_rundir: true

realcores: 2

wrfcores: 2

namelist:
  class: File
  path: 'real_wrf_test_input/namelist.input.uk9km'

metdir:
  class: Directory
  path: 'real_wrf_test_input/met_files'
    
rundir:
  class: Directory
  path: 'run_template'
  
wrfinputs:
  - class: File
    path: 'wrfinput_d01'

wrfbdys:
  - class: File
    path: 'wrfbdy_d01'